apiVersion: v1
kind: Pod
metadata:
  name: net3
  namespace: cxy
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: netexp
  restartPolicy: Always
