id: sshd5
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: sshd5
    containers:
      - name: master
        image: 121.40.171.96:5000/sshd
        cpu: 1000
        ports:
          - name: sshd
            containerPort: 22
        env:
          - key: NETWORK
            value: "test"
    nodeSelector:
      name: a1
labels:
  name: sshd