apiVersion: v1
kind: ReplicationController
metadata:
  name: sshd
  labels:
    name: sshd
spec:
  replicas: 3
  selector:
    name: sshd
  template:
    metadata:
      labels:
        name: sshd
    spec:
      containers:
      - name: sshdcontainer
        image: 10.10.103.215:5000/sshd
        ports:
        - containerPort: 80