id: sshd3
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: sshd3
    containers:
      - name: sshd3
        image: 10.10.103.215:5000/sshd
        ports:
          - name: sshd
            containerPort: 22
labels:
  name: sshd