id: sshd3
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: sshd3
    containers:
      - name: master
        image: 121.40.171.96:5000/sshd
        cpu: 1000
        ports:
          - name: sshd
            containerPort: 22
        env:
          - key: NETWORK
            value: "test"
labels:
  name: sshd